import ThemeRegistry from '@/mui/ThemeRegistry'
import type { Metadata } from 'next'
import MyAppBar from './_components/_client/MyAppBar'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <ThemeRegistry options={{ key: 'mui' }}>
        <MyAppBar>{children}</MyAppBar>
      </ThemeRegistry>
    </html>
  )
}
